config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :stars do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :show] do
    resources :reviews, only: [:create, :new]
    member do
      post :accept, :reject
    end
  end

  get "home", to: "pages#home" 
  get "mybookings", to: "pages#booking"
  get "ownedstars", to: "pages#ownedstars"
  get "profile", to: "pages#profile"

end

app/models/star.rb
class Star < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_title_and_synopsis,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo

  validates :name, presence: true
  validates :description, presence: true
  validates :description, length: { minimum: 5 }
  validates :registration_number, presence: true
  validates :price, presence: true
  validates :availability, presence: true, allow_blank: true
  validates :location, presence: true
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController

  def show
    @star = Star.find(params[:id])
    @booking = Booking.new
    @markers = [{
      lat: @star.user.latitude,
      lng: @star.user.longitude
    }]
  end

  def index
    @stars = Star.all
    if params[:query].present?
      @stars = Star.search_by_title_and_synopsis(params[:query])
    end
  end

  def new
    @star = Star.new
  end

  def create
    @star = Star.new(star_params)
    if @star.save
      redirect_to ownedstars_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @star = Star.find(params[:id])
  end

  def update
    @star = Star.find(params[:id])
    if @star.update(star_params)
      redirect_to star_path(@star)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @star = Star.find(params[:id])
    @star.destroy
    redirect_to ownedstar_path, status: :see_others
  end

  private
  def star_params
    params.require(:star).permit(:name, :description, :registration_number, :price, :availability, :location, :user_id, :photo)
  end
end

app/views/stars/_form.html.erb
<%= simple_form_for star do |f| %>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.input :description %>
  <%= f.input :registration_number %>
  <%= f.input :price %>
  <%= f.input :availability, input_html: { checked: true } %>
  <%= f.input :location %>
  <%= f.button :submit %>
<% end %>

app/views/stars/edit.html.erb
<div class="container">
<h1>Edit your star</h1>
<%= render "form", star: @star %>
</div>

app/views/stars/index.html.erb
<div id="nav-space"></div>
  <div id="wrapper">
  <h1>Find your star! 👇</h1>
    <div class="row justify-content-center mt-5">
        <%= form_with url: stars_path, method: :get, class: "d-flex " do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Type a keyword"
            %>
          <div class="container search">
          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>

  <div id="cards">
    <% @stars.each do |star|%>
      <%= link_to star_path(star) do %>
        <div class="card">
          <div class="icon">
            <svg xmlns="http://www.w3.org/2000/svg" height="16" width="18" viewBox="0 0 576 512">
            <path d="M316.9 18C311.6 7 300.4 0 288.1 0s-23.4 7-28.8 18L195 150.3 51.4 171.5c-12 1.8-22 10.2-25.7 21.7s-.7 24.2 7.9 32.7L137.8 329 113.2 474.7c-2 12 3 24.2 12.9 31.3s23 8 33.8 2.3l128.3-68.5 128.3 68.5c10.8 5.7 23.9 4.9 33.8-2.3s14.9-19.3 12.9-31.3L438.5 329 542.7 225.9c8.6-8.5 11.7-21.2 7.9-32.7s-13.7-19.9-25.7-21.7L381.2 150.3 316.9 18z"/>
            </svg>
          </div>
          <p class="title"><%= star.name%></p>
          <p class="text"><%= star.description%></p>
        </div>
      <% end %>
    <% end %>
  </div>
  </div>

app/views/stars/new.html.erb
<div class="container">
  <h1>Create a new star</h1>
    <%= render "form", star: @star %>
</div>

app/views/stars/show.html.erb
<div class="banner" id="bannerstar" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://getwallpapers.com/wallpaper/full/c/9/d/242226.jpg);">

  <div class="container">
    <div class="card-product">
      <%= image_tag @star.photo %>
        <div class="card-product-infos">
          <h1><%= @star.name %></h1>
            <h4 style ="color:white;">€<%= @star.price %> per night</h4>
              <p><%= @star.description %></p>
              <h6 style ="color:white;"><%=@star.registration_number %><h6>
            <%= link_to "Book the star", new_star_booking_path(@star.id), class:"btn" %>
        </div>
    </div>
  </div>
</div>

    <div class= "map-container">
      <div style="width: 100%; height: 25vh;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>
</div>