config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :stars do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :show] do
    resources :reviews, only: [:create, :new]
    member do
      post :accept, :reject
    end
  end

  get "home", to: "pages#home" 
  get "mybookings", to: "pages#booking"
  get "ownedstars", to: "pages#ownedstars"
  get "profile", to: "pages#profile"

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :star
  has_many :reviews, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :available_date

  private

  def available_date
    booked_dates = []
    @bookings = Booking.where(booking_status: true, star: self.star)
    @bookings.each do |booking|
      starting_date = booking.start_date
      ending_date = booking.end_date
      while ending_date >= starting_date
        booked_dates << starting_date.to_s
        starting_date += 1.days
      end
    end
    starting_date, ending_date = start_date, end_date
    while ending_date >= starting_date
      if booked_dates.include?(starting_date.to_s)
        self.errors.add(:start_date, :is_already_taken, message: "Some of the dates from your range are already taken")
      end
      starting_date += 1.days
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @star = Star.find(params[:star_id])
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
    @star = @booking.star
  end

  # def edit
  #   @booking = Booking.find(params[:id])
  # end

  # def update
  #   @booking = Booking.find(params[:id])
  #   @booking.update(booking_params)
  #   redirect_to stars_path(@stars)
  # end

  def create
    @booking = Booking.new(booking_params)
    @star = Star.find(params[:star_id])
    @booking.user = current_user
    @booking.star = @star
    if @booking.save
      redirect_to mybookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update!(booking_status: true)
    if @booking.booking_status
      redirect_to mybookings_path, notice: "Booking accepted"
    else
      redirect_to @booking, notice: "Booking could not be accepted, please try again"
    end
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.update(booking_status: false)
    if @booking.booking_status == false
      redirect_to @booking, notice: "Booking rejected"
    else
      redirect_to mybookings_path, notice: "Booking could not be rejected, please try again"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to mybookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:booking_status, :comment, :start_date, :end_date)
  end
end

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="row">
    <h3> Book this star </h3>
    <%= simple_form_for [@star, @booking] do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.input :comment, placeholder: "Enter a comment about the star here" %>
      <%= f.submit "Save",class: "btn btn-flat" %>
    <% end  %>
  </div>
</div>

app/views/bookings/show.html.erb
<%# can only accept or delete the booking, when deleted = rejected  %>
<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1>Booking for <%= @booking.star.name %> from <%= @booking.user.email %>, from the date <%=@booking.start_date%> to <%= @booking.end_date%></h1>
  </div>
  <div>
  <%if @booking.booking_status == true %>
  <p>This booking has been approved</p>
  <%end%>
  <%if @booking.booking_status == false %>
  <p>This booking has not been approved yet</p>
  <%end%>
  </div>

  <%= link_to "go back to the stars", stars_path(@stars), class: "btn btn-primary" %>

  <%= link_to "Delete this booking", booking_path(@booking), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?" }  %>

  <%if @star.user == current_user && @booking.booking_status == false%>
  <%= link_to "Confirm this booking", accept_booking_path(@booking), class: "btn btn-primary", data: { turbo_method: :post, turbo_confirm: "Are you sure you want to accept this booking?" }  %>
  <%= link_to "Reject this booking", reject_booking_path(@booking), class: "btn btn-primary", data: { turbo_method: :post, turbo_confirm: "Are you sure you want to decline this booking?" }  %>
  <%end%>
</div>