config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :stars do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :show] do
    resources :reviews, only: [:create, :new]
    member do
      post :accept, :reject
    end
  end

  get "home", to: "pages#home" 
  get "mybookings", to: "pages#booking"
  get "ownedstars", to: "pages#ownedstars"
  get "profile", to: "pages#profile"

end

app/views/pages/booking.html.erb
<div class = "spacelol" style = "background-image: url(https://getwallpapers.com/wallpaper/full/c/9/d/242226.jpg)"></div>
<div class="banner" style = "background-image: url(https://getwallpapers.com/wallpaper/full/c/9/d/242226.jpg)" >
  <div class = "booking-container">

    <div class = "booking-box">
    <%if @pendingbook.length > 0 %>
      <h2 class = "text-center", id = "text"> Pending Bookings of your stars!</h2>
    <%end%>
     <% @pendingbook.each do |booking| %>
     <% @star = booking.star%>
      <ul class= "card-booking">
          <li><strong>Star:</strong> <%=booking.star.name.capitalize%></li>
          <li><strong>Star Renter:</strong> <%=booking.user.first_name.capitalize%> <%= booking.user.last_name.capitalize%></li>
          <li><strong>Star Registration Number:</strong> <%=booking.star.registration_number%> </li>
          <li><strong>Price:</strong> £<%= (booking.star.price * (booking.end_date - booking.start_date)).round%></li>
          <li><strong>Date:</strong> <%= booking.start_date.strftime("%A, %d %B %Y")%> to <%= booking.end_date.strftime("%A, %d %B %Y")%></li>
        <% if booking.booking_status == true%>
          <li class = "mb-2"><strong>Status:</strong> Approved</li>
        <%else%>
          <li class = "mb-2"><strong>Status:</strong> Not Approved</li>
      <%end%>
          <%= link_to "Confirm this booking", accept_booking_path(booking), class: "btn btn-primary", id: "approve", data: { turbo_method: :post, turbo_confirm: "Are you sure you want to accept this booking?" }  %>
          <%= link_to "Reject this booking", booking_path(booking), class: "btn btn-primary", id: "cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to reject this booking?" }  %>
        </ul>
     <%end%>

    </div>

    <div class = "booking-box ps-4">
      <%if @bookings.length > 0 %>
        <h2 class="text-center" id = "text">View your bookings!</h2>
      <%end%>
        <% @bookings.each do |booking|%>
        <% @star = booking.star%>
          <ul class = "card-booking">
            <li><strong>Star:</strong> <%= booking.star.name.capitalize%></li>
            <li><strong>Renter:</strong> <%= current_user.first_name.capitalize%> <%= current_user.last_name.capitalize%></li>
            <li><strong>Star Registration Number:</strong> <%=booking.star.registration_number%> </li>
            <li><strong>Price:</strong> £<%= (booking.star.price * (booking.end_date - booking.start_date)).round%></li>
            <li><strong>Date:</strong> <%= booking.start_date.strftime("%A, %d %B %Y")%> to <%= booking.end_date.strftime("%A, %d %B %Y") %> </li>
          <% if booking.booking_status == true%>
            <li class = "mb-2"><strong>Status:</strong> Approved</li>
          <%else%>
            <li class = "mb-2"><strong>Status:</strong> Not Approved</li>
          <%end%>
          <%if Date.today > booking.end_date%>
            <%if booking.booking_status == true%>
            <%= link_to "Review booking", new_booking_review_path(booking), class: "btn btn-primary", id: "reviewbook"%></li>
            <%end%>
            <%= link_to "Remove old booking", booking_path(booking), class: "btn btn-cancel", id: "cancelbook", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?" }  %>
          <%else%>
            <%= link_to "Cancel this booking", booking_path(booking), class: "btn btn-cancel", id: "cancelbook", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?" }  %>
          <%end%>
          </ul>
        <%end%>
    </div>

  </div>
</div>
"

app/views/pages/editprofile.html.erb
<%= simple_form_for profile_path do |f| %>
  <%= f.input :first_name, label: "First Name"%>
  <%= f.input :last_name, label: "Last Name"%>
  <%= f.input :address, label: "Your address"%>
  <%= f.input :user_description, label: "Your description" %>
  <%= f.input :current_password,
                hint: "we need your current password to confirm your changes",
                required: true,
                input_html: { autocomplete: "current-password" } %>
  <%= f.button :submit%>
<%end%>

app/views/pages/home.html.erb
<div class="wrapper">
  <div class="banner video">
    <video src="https://res.cloudinary.com/dgxlwwwxg/video/upload/v1701342378/Galaxy_scene_3d_mtrxo0.mp4" muted autoplay loop>
    </video>
      <div class="main-text">
        <h2>Let's go for a walk...</h2>
                <h1>...On the Stars</h1>
                    <p>
                      And reach for the stars
                    </p>
                    <div class="container">
                  <%= link_to "Stars", stars_path, class: "buttonA" %>
                </div>
      </div>
  </div>
</div>

app/views/pages/ownedstars.html.erb
<h1>Stars I own! MUHAHAH MY INFINITE EMPIRE</h1>
<% @stars.each do |star|%>
<p> <%= star.name%> is my epic stars name<p>
<%= link_to "See star details", star_path(star) %>
<%= link_to "delete a star ", star_path(star), data: {turbo_method: :delete, turbo_confirm: "are you sure you want to delete star"}, class: "btn"%>
<%= link_to "edit a star ", edit_star_path(star) %>
<%end%>

<%= link_to "create a star", new_star_path, class: "btn"%>
<%= link_to "back to home", home_path, class: "btn"%>

app/views/pages/profile.html.erb
<h1>Your profile!</h1>
<p>Your name is <%=@profile.first_name%></p>
<p>Your last name is <%= @profile.last_name%></p>
<p>Your address is <%= @profile.address%></p>
<p>Your description is <%= @profile.user_description%>

<h2> Would you like to edit your profile?</h2>
<%= link_to "edit profile", edit_user_registration_path%>

<div>
<%= link_to "back to home", home_path%>
</div>